### PR TITLE
Change to client_id

### PR DESCRIPTION
**Pull request by dbfx**
Castle seems to require snakecase and not camelcase.

### CODE REVIEW

**Comment by joladev** [comment]
Hi! Appreciate the PR, but it seems to be breaking some tests. If you have the time, please take a look at fixing the tests. Otherwise, I'll take care of it when I'm free.

**Comment by dbfx** [comment]
> 
> 
> Hi! Appreciate the PR, but it seems to be breaking some tests. If you have the time, please take a look at fixing the tests. Otherwise, I'll take care of it when I'm free.

Sure thing, I think I've fixed it now but the 7.2 compile error is actually  more complicated. It's because of this: 

Fatal error: Declaration of Castle_TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/travis/build/castle/castle-php/test/Castle.php on line 3

phpUnit setUp hint is void, where your test is not. I suspect this has been broken for a while, and I could add it but probably the whole of 7.2 is broken due to the changes in phpUnit?

**Comment by joladev** [comment]
@dbfx yeah, adding `:void` to the end of all the `setup` definitions fixes it. I can take over the PR and fix it or you can apply this diff

```
diff --git a/test/Castle.php b/test/Castle.php
index 062a6e7..82ecd58 100644
--- a/test/Castle.php
+++ b/test/Castle.php
@@ -2,7 +2,7 @@
 
 abstract class Castle_TestCase extends \PHPUnit\Framework\TestCase
 {
-  public function setUp()
+  public function setUp(): void
   {
     Castle::setApiKey('secret');
   }
diff --git a/test/CastleTest.php b/test/CastleTest.php
index daa667a..e9b131a 100644
--- a/test/CastleTest.php
+++ b/test/CastleTest.php
@@ -8,7 +8,7 @@ public static function setUpBeforeClass() {
     Castle::setApiKey('secretkey');
   }
 
-  public function setUp()
+  public function setUp(): void
   {
     $_SESSION = array();
     $_COOKIE = array();
diff --git a/test/ErrorsTest.php b/test/ErrorsTest.php
index c2e7bb7..8a50eae 100644
--- a/test/ErrorsTest.php
+++ b/test/ErrorsTest.php
@@ -3,7 +3,7 @@
 class CastleErrorTest extends Castle_TestCase
 {
 
-  public function setUp()
+  public function setUp(): void
   {
     $_SERVER['HTTP_USER_AGENT'] = 'TestAgent';
     $_SERVER['REMOTE_ADDR'] = '8.8.8.8';
diff --git a/test/RequestContextTest.php b/test/RequestContextTest.php
index a863431..c081d04 100644
--- a/test/RequestContextTest.php
+++ b/test/RequestContextTest.php
@@ -9,7 +9,7 @@ public static function setUpBeforeClass() {
     unset($_SERVER['HTTP_X_FORWARDED_FOR']);
   }
 
-  public function setUp() {
+  public function setUp(): void {
     $_COOKIE = array();
   }
 
diff --git a/test/RequestTest.php b/test/RequestTest.php
index 742482b..d0f5b24 100644
--- a/test/RequestTest.php
+++ b/test/RequestTest.php
@@ -12,7 +12,7 @@ public static function setUpBeforeClass()
     Castle::setUseWhitelist(false);
   }
 
-  public function setUp()
+  public function setUp(): void
   {
     $_COOKIE = array();
     $_SESSION = array();

```

**Comment by dbfx** [comment]
I think you better take over. It wont be 5.6 compatible which you are also
testing for so it's probably best you decide where to go :)

Thanks for the help!

**Comment by joladev** [comment]
@dbfx the mystery is how the 7.2 builds ran successfully last year! I'll try to dig into it and get back to you as soon as possible

**Comment by joladev** [comment]
@dbfx alright, we've decided to drop support for PHP5 and if you rebase on master you should be all green. We'll make a major release after this.

**Comment by dbfx** [comment]
Great, I think that's best! Thanks for the help :)

**Comment by joladev** [comment]
I was trying to be fancy and update your fork branch. No idea what happened but not able to reopen this. Created new PR with your changes https://github.com/castle/castle-php/pull/31

**Pull request closed without merging**
